version: '3'
services:
  notebook:
    image: jupyter/scipy-notebook
    ports:
      - "9988:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight-2
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis_data: